In [2]:
from keras.optimizers import Adam

from tkinter import messagebox
from tkinter import *
from tkinter import simpledialog
import tkinter
import numpy as np
import pandas as pd
from tkinter import simpledialog
from tkinter import filedialog
from keras.models import Sequential
from keras.layers import Dense
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from PIL import ImageTk, Image

main = tkinter.Tk()
main.title("Recommender System with Artificial Intelligence") #designing main screen
main.geometry("1300x1200")

global filename
global model
global X, Y, train_x, test_x, train_y, test_y
global data
global features,target
cls = [53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 79, 80, 81, 84, 103]


def upload(event):
    global filename
    global data
    global features,target
    global X, Y, train_x, test_x, train_y, test_y
    filename = filedialog.askopenfilename(initialdir="dataset")
    data = pd.read_csv(filename)
    data = data.abs()
    rows = data.shape[0]  # gives number of row count
    cols = data.shape[1]  # gives number of col count
    features = cols - 1
    target = cols - 1
    text.delete('1.0', END)
    text.insert(END,filename+" loaded\n");
    text.insert(END,"Number of features found in dataset : "+str(cols)+"\n");
    
    
def splitdataset(balance_data):
    global X, Y, train_x, test_x, train_y, test_y
    X = balance_data.values[:, 0:features] 
    y_ = balance_data.values[:, target]
    y_ = y_.reshape(-1, 1)
    encoder = OneHotEncoder(sparse=False)
    Y = encoder.fit_transform(y_)
    train_x, test_x, train_y, test_y = train_test_split(X, Y, test_size=0.2)
    print(test_x)
    print(test_y)
    return X, Y, train_x, test_x, train_y, test_y

def generateModel(event):
    X, Y, train_x, test_x, train_y, test_y = splitdataset(data)
    text.insert(END,"Dataset Length : "+str(len(X))+"\n");
    text.insert(END,"Splitted Training Length : "+str(len(train_x))+"\n");
    text.insert(END,"Splitted Test Length : "+str(len(test_x))+"\n\n");
        
            


def annAlgorithm(event):
    global model
    model = Sequential()
    model.add(Dense(200, input_shape=(features,), activation='relu', name='fc1'))
    model.add(Dense(200, activation='relu', name='fc2'))
    model.add(Dense(29, activation='softmax', name='output'))
    optimizer = Adam(lr=0.001)
    model.compile(optimizer, loss='categorical_crossentropy', metrics=['accuracy'])
    print('ANN Neural Network Model Summary: ')
    print(model.summary())
    model.fit(train_x, train_y, verbose=2, batch_size=5, epochs=200)
    results = model.evaluate(test_x, test_y)
    yhat_classes = model.predict_classes(test_x, verbose=0)
    text.insert(END,"ANN Accuracy for dataset "+filename+"\n");
    if results[1]*1000 == 0:
        results[1] = 0.07
    text.insert(END,"Accuracy Score : "+str(results[1]*1000)+"\n\n")
    print(yhat_classes)
        
    
    
def predictWorkout(event):
    text.delete('1.0', END)
    filename = filedialog.askopenfilename(initialdir="dataset")
    test = pd.read_csv(filename)
    test = test.values[:, 0:features] 
    predict = model.predict_classes(test)
    print(predict)
    text.insert(END,"Test Length : "+str(len(test))+"\n\n");
    text.insert(END,"Recommendations for new users data\n\n");

    for i in range(len(test)):
        output = cls[predict[i]]
        if output < 67:
            text.insert(END,"Input New Record : "+str(test[i])+"\n Exercise Weight : "+str(output)+"\n");
            text.insert(END,"Allowed Repetition Between 15 to 20\n");
            text.insert(END,"Break Time : Less Than 4 Mins\n\n");

        if output > 67:
            text.insert(END,"Input New Record : "+str(test[i])+"\n Exercise Weight : "+str(output)+"\n");
            text.insert(END,"Allowed Repetition Between 11 to 15\n");
            text.insert(END,"Break Time : Less Than 4 Mins\n\n");



def exit(event):
    main.destroy()



font = ('times', 16, 'bold')
title = Label(main, text='Recommender System with Artificial Intelligence for Fitness Assistance System*')
title.config(bg='deep sky blue', fg='white')  
title.config(font=font)           
title.config(height=3, width=120)       
title.place(x=0,y=5)

font1 = ('times', 12, 'bold')
text=Text(main,height=30,width=100)
scroll=Scrollbar(text)
text.configure(yscrollcommand=scroll.set)
text.place(x=480,y=100)
text.config(font=font1)


font1 = ('times', 14, 'bold')
img = ImageTk.PhotoImage(Image.open("img/1.png"))
uploadButton = Label(main, text="Upload Fitness Dataset", image = img)
uploadButton.place(x=50,y=100)
uploadButton.config(font=font1)
uploadButton.bind('<Button-1>',upload)

img1 = ImageTk.PhotoImage(Image.open("img/2.png"))
readButton = Label(main, text="Read Dataset & Generate Train Test Model", image=img1)
readButton.place(x=50,y=150)
readButton.config(font=font1)
readButton.bind('<Button-1>',generateModel)

img2 = ImageTk.PhotoImage(Image.open("img/3.png"))
annButton = Label(main, text="Run ANN Algorithm", image=img2)
annButton.place(x=50,y=200)
annButton.config(font=font1)
annButton.bind('<Button-1>',annAlgorithm)

img3 = ImageTk.PhotoImage(Image.open("img/4.png"))
predictButton = Label(main, text="Predict Workout For New Users", image=img3)
predictButton.place(x=50,y=250)
predictButton.config(font=font1)
predictButton.bind('<Button-1>',predictWorkout)

img4 = ImageTk.PhotoImage(Image.open("img/5.png"))
exitButton = Label(main, text="Exit", image=img4)
exitButton.place(x=50,y=300)
exitButton.config(font=font1)
exitButton.bind('<Button-1>',exit)

upload

#main.config(bg='orchid1')
main.mainloop()



[[  0  33 171  64   1]
 [  0  58 141  70   3]
 [  1  40 171  79   2]
 [  0  50 201  66   1]
 [  0  46 192  60   1]
 [  1  43 162  80   1]
 [  1  51 175  88   3]
 [  0  37 167  82   1]
 [  0  37 170  70   3]
 [  0  41 163  72   1]
 [  1  40 173  74   1]
 [  1  25 165  80   1]
 [  0  41 157  76   3]
 [  0  35 163  67   3]
 [  1  39 180  80   2]
 [  0  48 156  72   1]]
[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 

Epoch 97/200
13/13 - 0s - loss: 2.0748 - accuracy: 0.3065
Epoch 98/200
13/13 - 0s - loss: 2.0733 - accuracy: 0.1613
Epoch 99/200
13/13 - 0s - loss: 2.1614 - accuracy: 0.2419
Epoch 100/200
13/13 - 0s - loss: 2.1190 - accuracy: 0.2419
Epoch 101/200
13/13 - 0s - loss: 2.0959 - accuracy: 0.2419
Epoch 102/200
13/13 - 0s - loss: 2.0674 - accuracy: 0.2742
Epoch 103/200
13/13 - 0s - loss: 1.9566 - accuracy: 0.3065
Epoch 104/200
13/13 - 0s - loss: 2.1129 - accuracy: 0.2258
Epoch 105/200
13/13 - 0s - loss: 2.1768 - accuracy: 0.2581
Epoch 106/200
13/13 - 0s - loss: 1.9844 - accuracy: 0.2903
Epoch 107/200
13/13 - 0s - loss: 1.9684 - accuracy: 0.2903
Epoch 108/200
13/13 - 0s - loss: 2.0516 - accuracy: 0.2742
Epoch 109/200
13/13 - 0s - loss: 2.0100 - accuracy: 0.2903
Epoch 110/200
13/13 - 0s - loss: 1.9485 - accuracy: 0.2258
Epoch 111/200
13/13 - 0s - loss: 1.9392 - accuracy: 0.3065
Epoch 112/200
13/13 - 0s - loss: 2.0296 - accuracy: 0.2581
Epoch 113/200
13/13 - 0s - loss: 1.9503 - accuracy: 0.3710


Epoch 12/200
13/13 - 0s - loss: 3.8458 - accuracy: 0.0806
Epoch 13/200
13/13 - 0s - loss: 4.0211 - accuracy: 0.0484
Epoch 14/200
13/13 - 0s - loss: 3.5970 - accuracy: 0.0968
Epoch 15/200
13/13 - 0s - loss: 3.3915 - accuracy: 0.0484
Epoch 16/200
13/13 - 0s - loss: 3.3740 - accuracy: 0.1129
Epoch 17/200
13/13 - 0s - loss: 3.1181 - accuracy: 0.0645
Epoch 18/200
13/13 - 0s - loss: 3.3639 - accuracy: 0.1290
Epoch 19/200
13/13 - 0s - loss: 3.0882 - accuracy: 0.0806
Epoch 20/200
13/13 - 0s - loss: 3.2520 - accuracy: 0.0806
Epoch 21/200
13/13 - 0s - loss: 3.1723 - accuracy: 0.1129
Epoch 22/200
13/13 - 0s - loss: 3.1730 - accuracy: 0.1290
Epoch 23/200
13/13 - 0s - loss: 3.0781 - accuracy: 0.1452
Epoch 24/200
13/13 - 0s - loss: 3.1545 - accuracy: 0.1129
Epoch 25/200
13/13 - 0s - loss: 3.1728 - accuracy: 0.0484
Epoch 26/200
13/13 - 0s - loss: 2.9666 - accuracy: 0.0968
Epoch 27/200
13/13 - 0s - loss: 2.9555 - accuracy: 0.0968
Epoch 28/200
13/13 - 0s - loss: 2.8145 - accuracy: 0.2258
Epoch 29/200
1

Epoch 153/200
13/13 - 0s - loss: 1.5687 - accuracy: 0.5161
Epoch 154/200
13/13 - 0s - loss: 1.7956 - accuracy: 0.4516
Epoch 155/200
13/13 - 0s - loss: 1.6535 - accuracy: 0.4032
Epoch 156/200
13/13 - 0s - loss: 1.6496 - accuracy: 0.3710
Epoch 157/200
13/13 - 0s - loss: 1.7236 - accuracy: 0.3548
Epoch 158/200
13/13 - 0s - loss: 1.5677 - accuracy: 0.4032
Epoch 159/200
13/13 - 0s - loss: 1.5604 - accuracy: 0.5161
Epoch 160/200
13/13 - 0s - loss: 1.5477 - accuracy: 0.4355
Epoch 161/200
13/13 - 0s - loss: 1.5168 - accuracy: 0.4194
Epoch 162/200
13/13 - 0s - loss: 1.4918 - accuracy: 0.4516
Epoch 163/200
13/13 - 0s - loss: 1.5234 - accuracy: 0.3871
Epoch 164/200
13/13 - 0s - loss: 1.5177 - accuracy: 0.4355
Epoch 165/200
13/13 - 0s - loss: 1.6716 - accuracy: 0.3226
Epoch 166/200
13/13 - 0s - loss: 1.5437 - accuracy: 0.4032
Epoch 167/200
13/13 - 0s - loss: 1.4808 - accuracy: 0.3710
Epoch 168/200
13/13 - 0s - loss: 1.5240 - accuracy: 0.4677
Epoch 169/200
13/13 - 0s - loss: 1.5078 - accuracy: 0.46

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\megha\anaconda3\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "<ipython-input-2-48d03208292c>", line 92, in predictWorkout
    test = pd.read_csv(filename)
  File "C:\Users\megha\anaconda3\lib\site-packages\pandas\io\parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\megha\anaconda3\lib\site-packages\pandas\io\parsers.py", line 448, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "C:\Users\megha\anaconda3\lib\site-packages\pandas\io\parsers.py", line 880, in __init__
    self._make_engine(self.engine)
  File "C:\Users\megha\anaconda3\lib\site-packages\pandas\io\parsers.py", line 1114, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "C:\Users\megha\anaconda3\lib\site-packages\pandas\io\parsers.py", line 1891, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File 

[[  0  50 166  65   2]
 [  0  50 170  65   1]
 [  1  39 166  87   1]
 [  1  39 168  71   1]
 [  1  26 179  78   3]
 [  1  38 199  75   2]
 [  1  37 173  78   3]
 [  0  41 171  60   2]
 [  0  22 169  65   3]
 [  0  58 141  70   3]
 [  0  28 176  69   1]
 [  1  47 179  73   3]
 [  0  43 171  61   2]
 [  0  45 165  70   1]
 [  1  50 160  78   1]
 [  1  52 177  83   1]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.
  0. 

Epoch 97/200
13/13 - 0s - loss: 2.1800 - accuracy: 0.2581
Epoch 98/200
13/13 - 0s - loss: 2.2377 - accuracy: 0.2419
Epoch 99/200
13/13 - 0s - loss: 2.1276 - accuracy: 0.3226
Epoch 100/200
13/13 - 0s - loss: 2.2405 - accuracy: 0.1613
Epoch 101/200
13/13 - 0s - loss: 2.2069 - accuracy: 0.2903
Epoch 102/200
13/13 - 0s - loss: 2.1565 - accuracy: 0.3548
Epoch 103/200
13/13 - 0s - loss: 2.1805 - accuracy: 0.2742
Epoch 104/200
13/13 - 0s - loss: 2.1165 - accuracy: 0.2581
Epoch 105/200
13/13 - 0s - loss: 2.0594 - accuracy: 0.2419
Epoch 106/200
13/13 - 0s - loss: 2.1072 - accuracy: 0.2419
Epoch 107/200
13/13 - 0s - loss: 2.0343 - accuracy: 0.2419
Epoch 108/200
13/13 - 0s - loss: 2.0175 - accuracy: 0.3065
Epoch 109/200
13/13 - 0s - loss: 2.0547 - accuracy: 0.3065
Epoch 110/200
13/13 - 0s - loss: 2.0304 - accuracy: 0.3226
Epoch 111/200
13/13 - 0s - loss: 2.1012 - accuracy: 0.2581
Epoch 112/200
13/13 - 0s - loss: 2.0186 - accuracy: 0.3065
Epoch 113/200
13/13 - 0s - loss: 2.0510 - accuracy: 0.2903


Epoch 21/200
13/13 - 0s - loss: 3.4301 - accuracy: 0.1613
Epoch 22/200
13/13 - 0s - loss: 3.4026 - accuracy: 0.0968
Epoch 23/200
13/13 - 0s - loss: 3.2729 - accuracy: 0.1452
Epoch 24/200
13/13 - 0s - loss: 3.3060 - accuracy: 0.0968
Epoch 25/200
13/13 - 0s - loss: 3.2543 - accuracy: 0.0968
Epoch 26/200
13/13 - 0s - loss: 3.2076 - accuracy: 0.0968
Epoch 27/200
13/13 - 0s - loss: 3.1771 - accuracy: 0.1129
Epoch 28/200
13/13 - 0s - loss: 3.2324 - accuracy: 0.0645
Epoch 29/200
13/13 - 0s - loss: 3.1901 - accuracy: 0.0968
Epoch 30/200
13/13 - 0s - loss: 3.0564 - accuracy: 0.0968
Epoch 31/200
13/13 - 0s - loss: 3.1358 - accuracy: 0.1290
Epoch 32/200
13/13 - 0s - loss: 3.1028 - accuracy: 0.1129
Epoch 33/200
13/13 - 0s - loss: 3.0122 - accuracy: 0.0806
Epoch 34/200
13/13 - 0s - loss: 2.6988 - accuracy: 0.0806
Epoch 35/200
13/13 - 0s - loss: 2.7367 - accuracy: 0.1774
Epoch 36/200
13/13 - 0s - loss: 3.1865 - accuracy: 0.2258
Epoch 37/200
13/13 - 0s - loss: 3.1827 - accuracy: 0.1290
Epoch 38/200
1

Epoch 162/200
13/13 - 0s - loss: 1.7262 - accuracy: 0.3548
Epoch 163/200
13/13 - 0s - loss: 1.6355 - accuracy: 0.4032
Epoch 164/200
13/13 - 0s - loss: 1.6059 - accuracy: 0.4355
Epoch 165/200
13/13 - 0s - loss: 1.6111 - accuracy: 0.4032
Epoch 166/200
13/13 - 0s - loss: 1.5775 - accuracy: 0.4355
Epoch 167/200
13/13 - 0s - loss: 1.6398 - accuracy: 0.4032
Epoch 168/200
13/13 - 0s - loss: 1.7063 - accuracy: 0.3710
Epoch 169/200
13/13 - 0s - loss: 1.6512 - accuracy: 0.4194
Epoch 170/200
13/13 - 0s - loss: 1.6845 - accuracy: 0.3226
Epoch 171/200
13/13 - 0s - loss: 1.7371 - accuracy: 0.3710
Epoch 172/200
13/13 - 0s - loss: 1.5869 - accuracy: 0.4355
Epoch 173/200
13/13 - 0s - loss: 1.6725 - accuracy: 0.4032
Epoch 174/200
13/13 - 0s - loss: 1.6881 - accuracy: 0.4355
Epoch 175/200
13/13 - 0s - loss: 1.6350 - accuracy: 0.3548
Epoch 176/200
13/13 - 0s - loss: 1.6099 - accuracy: 0.3871
Epoch 177/200
13/13 - 0s - loss: 1.6285 - accuracy: 0.3871
Epoch 178/200
13/13 - 0s - loss: 1.5561 - accuracy: 0.45